language: ruby
sudo: required
dist: trusty

env:
  - CXX=g++-4.8

addons:
  postgresql: "9.5"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  bundler: true

branches:
  only:
  - master
  - staging
  - stable

services:
  - postgresql

install:
  - bundle install --path vendor/bundle

before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

script:
  - set -e
  - bundle exec rake
