language: ruby
sudo: required
dist: trusty

env:
  - CXX=g++-4.8

addons:
  postgresql: "9.5"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  bundler: true

branches:
  only:
  - master
  - staging
  - stable

services:
  - postgresql

install:
  - bundle install

script:
  - rspec
